services:
  - type: web
    name: just4u-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_SECRET
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CONTACT_EMAIL
        sync: false
      - key: SMTP_URL
        sync: false